export const categoriesData = [
    { name: "Food & Dining", url: "#food-dining" },
    { name: "Medicines", url: "#medicines" },
    { name: "Automotive", url: "#automotive" },
    { name: "Services", url: "#services" },
    { name: "Jewellery", url: "#jewellery" },
    { name: "Clothing", url: "#clothing" },
    { name: "Beauty Products", url: "#beauty-products" },
    { name: "Footwear", url: "#footwear" },
    { name: "Groceries", url: "#groceries" },
    { name: "Fruits", url: "#fruits" },
    { name: "Books", url: "#books" },
    { name: "Pet Food", url: "#pet-food" },
    { name: "Musical Instruments", url: "#musical-instruments" },
    { name: "Home Furniture", url: "#home-furniture" },
    { name: "Bags", url: "#bags" },
    { name: "Kitchen Products", url: "#kitchen-products" },
    { name: "Sports & Fitness", url: "#sports-fitness" },
  { name: "Home Decor", url: "#home-decor" },
    { name: "Watches", url: "#watches" },
    { name: "Organic Veggies & Fruits", url: "#organic" },
];